service: triage-serverless

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_USUARIOS_TABLE: t_usuarios
    DYNAMODB_TOKENS_TABLE: t_tokens_acceso
    DYNAMODB_TICKETS_TABLE: t_tickets
    SQS_QUEUE_URL: !Ref TicketsQueue
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}

  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole

custom:
  pythonRequirements:
    dockerizePip: true

functions:

  CrearUsuario:
    handler: src/auth/crear_usuario.lambda_handler
    events:
      - http:
          path: /auth/usuarios
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  LoginUsuario:
    handler: src/auth/login_usuario.lambda_handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  LogoutUsuario:
    handler: src/auth/logout.lambda_handler
    events:
      - http:
          path: /auth/logout
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  ValidarTokenAcceso:
    handler: src/auth/validar_token.lambda_handler
    events:
      - http:
          path: /auth/validar
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  ActualizarAreas:
    handler: src/auth/actualizar_areas.lambda_handler
    events:
      - http:
          path: /auth/empresas/areas
          method: put
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  ActualizarUsuario:
    handler: src/auth/actualizar_usuario.lambda_handler
    events:
      - http:
          path: /auth/usuarios/modificar
          method: put
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }
  
  ObtenerEmpleados:
    handler: src/auth/mostrar_empleados.lambda_handler
    events:
      - http:
          path: /auth/empleados
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }


  CargarCsv:
    handler: src/tickets/cargar_csv.lambda_handler
    events:
      - http:
          path: /tickets/csv
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  ClasificarTicket:
    handler: src/tickets/clasificar_ticket.lambda_handler
    environment:
      GROQ_API_KEY: ${env:GROQ_API_KEY} 
    events:
      - sqs:
          arn: !GetAtt TicketsQueue.Arn
          batchSize: 1 

  ObtenerTickets:
    handler: src/tickets/obtener_tickets.lambda_handler
    events:
      - http:
          path: /tickets
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body,
                  "queryStringParameters": {
                    "tenant_area": "$input.params('tenant_area')",
                    "tenant_id": "$input.params('tenant_id')"
                  }
                }

  ResolverTicket:
      handler: src/tickets/resolver_ticket.lambda_handler
      environment:
        TICKETS_SNS_TOPIC_ARN: !Ref TicketsResueltosTopic 
      events:
        - http:
            path: /tickets/{ticket_id}/resolver
            method: put
            cors: true
            integration: lambda
            request:
              template:
                application/json: |
                  {
                    "method": "$context.httpMethod",
                    "path": "$context.path",
                    "headers": {
                      "Authorization": "$input.params('Authorization')"
                    },
                    "body": $input.body,
                    "pathParameters": {
                      "ticket_id": "$input.params('ticket_id')"
                    }
                  }

  EnviarCorreoNotificacion:
      handler: src/tickets/enviar_email.lambda_handler
      environment:
        RESEND_API_KEY: ${env:RESEND_API_KEY} 
      events:
        - sns:
            arn: !Ref TicketsResueltosTopic 
            topicName: TicketsResueltosTopic

resources:
  Resources:
    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_usuarios
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: correo
            AttributeType: S
          - AttributeName: rol
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: correo
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: RolIndex
            KeySchema:
              - AttributeName: rol
                KeyType: HASH
              - AttributeName: tenant_id
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - nombre_empresa
                - areas
                - correo
                - area          

    TablaTokensAcceso:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_tokens_acceso
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    TablaTickets:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_tickets
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: ticket_id
            AttributeType: S
          - AttributeName: tenant_area
            AttributeType: S
          - AttributeName: score
            AttributeType: N
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: ticket_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: AreaScoreIndex
            KeySchema:
              - AttributeName: tenant_area
                KeyType: HASH
              - AttributeName: score
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    TicketsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TicketsQueue
        VisibilityTimeout: 60
        MessageRetentionPeriod: 86400  
    TicketsResueltosTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: TicketsResueltosTopic
